// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/plugin/v1/plugin.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mensagem vazia para o request de descoberta, o plugin deve apenas retornar o que ele sabe.
type DiscoveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryRequest) Reset() {
	*x = DiscoveryRequest{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryRequest) ProtoMessage() {}

func (x *DiscoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryRequest.ProtoReflect.Descriptor instead.
func (*DiscoveryRequest) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

// Resposta contendo a lista de ferramentas que o plugin expõe.
type DiscoveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*Tool                `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryResponse) Reset() {
	*x = DiscoveryResponse{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryResponse) ProtoMessage() {}

func (x *DiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryResponse.ProtoReflect.Descriptor instead.
func (*DiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *DiscoveryResponse) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

// Representa uma ferramenta que o agente pode usar.
type Tool struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Nome único da ferramenta dentro deste plugin (ex: "pesquisar_banco", "reiniciar_servidor").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Descrição do que a ferramenta faz, usada pelo agente para decidir quando chamá-la.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// O JSON Schema (em formato de string) que descreve os argumentos esperados pela ferramenta.
	// Deve ser compatível com o padrão JSON Schema e será fornecido ao LLM.
	InputSchemaJson string `protobuf:"bytes,3,opt,name=input_schema_json,json=inputSchemaJson,proto3" json:"input_schema_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *Tool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tool) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tool) GetInputSchemaJson() string {
	if x != nil {
		return x.InputSchemaJson
	}
	return ""
}

// Requisição para executar uma ferramenta.
type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// O nome da ferramenta a ser executada (deve ser um dos nomes retornados no Discovery).
	ToolName string `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// Os argumentos fornecidos pelo agente para a ferramenta, codificados como uma string JSON.
	// Esta string deve validar contra o input_schema_json fornecido no Discovery.
	ArgumentsJson string `protobuf:"bytes,2,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ExecuteRequest) GetArgumentsJson() string {
	if x != nil {
		return x.ArgumentsJson
	}
	return ""
}

// Resposta da execução da ferramenta.
type ExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// O resultado da execução da ferramenta. Este conteúdo será passado de volta ao agente.
	// Pode ser texto simples, JSON, ou qualquer string, dependendo da ferramenta.
	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// Indica se a execução encontrou um erro.
	// Se true, o 'result' geralmente conterá a mensagem de erro.
	IsError       bool `protobuf:"varint,2,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_api_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ExecuteResponse) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

var File_api_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_api_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/plugin/v1/plugin.proto\x12\x12picoclip.plugin.v1\"\x12\n" +
	"\x10DiscoveryRequest\"C\n" +
	"\x11DiscoveryResponse\x12.\n" +
	"\x05tools\x18\x01 \x03(\v2\x18.picoclip.plugin.v1.ToolR\x05tools\"h\n" +
	"\x04Tool\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12*\n" +
	"\x11input_schema_json\x18\x03 \x01(\tR\x0finputSchemaJson\"T\n" +
	"\x0eExecuteRequest\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12%\n" +
	"\x0earguments_json\x18\x02 \x01(\tR\rargumentsJson\"D\n" +
	"\x0fExecuteResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x19\n" +
	"\bis_error\x18\x02 \x01(\bR\aisError2\xc1\x01\n" +
	"\rPluginService\x12Z\n" +
	"\tDiscovery\x12$.picoclip.plugin.v1.DiscoveryRequest\x1a%.picoclip.plugin.v1.DiscoveryResponse\"\x00\x12T\n" +
	"\aExecute\x12\".picoclip.plugin.v1.ExecuteRequest\x1a#.picoclip.plugin.v1.ExecuteResponse\"\x00B!Z\x1fpicoclip/api/plugin/v1;pluginv1b\x06proto3"

var (
	file_api_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_api_plugin_v1_plugin_proto_rawDescData []byte
)

func file_api_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_api_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_api_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_plugin_v1_plugin_proto_rawDesc), len(file_api_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_api_plugin_v1_plugin_proto_rawDescData
}

var file_api_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_plugin_v1_plugin_proto_goTypes = []any{
	(*DiscoveryRequest)(nil),  // 0: picoclip.plugin.v1.DiscoveryRequest
	(*DiscoveryResponse)(nil), // 1: picoclip.plugin.v1.DiscoveryResponse
	(*Tool)(nil),              // 2: picoclip.plugin.v1.Tool
	(*ExecuteRequest)(nil),    // 3: picoclip.plugin.v1.ExecuteRequest
	(*ExecuteResponse)(nil),   // 4: picoclip.plugin.v1.ExecuteResponse
}
var file_api_plugin_v1_plugin_proto_depIdxs = []int32{
	2, // 0: picoclip.plugin.v1.DiscoveryResponse.tools:type_name -> picoclip.plugin.v1.Tool
	0, // 1: picoclip.plugin.v1.PluginService.Discovery:input_type -> picoclip.plugin.v1.DiscoveryRequest
	3, // 2: picoclip.plugin.v1.PluginService.Execute:input_type -> picoclip.plugin.v1.ExecuteRequest
	1, // 3: picoclip.plugin.v1.PluginService.Discovery:output_type -> picoclip.plugin.v1.DiscoveryResponse
	4, // 4: picoclip.plugin.v1.PluginService.Execute:output_type -> picoclip.plugin.v1.ExecuteResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_plugin_v1_plugin_proto_init() }
func file_api_plugin_v1_plugin_proto_init() {
	if File_api_plugin_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_plugin_v1_plugin_proto_rawDesc), len(file_api_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_api_plugin_v1_plugin_proto_depIdxs,
		MessageInfos:      file_api_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_api_plugin_v1_plugin_proto = out.File
	file_api_plugin_v1_plugin_proto_goTypes = nil
	file_api_plugin_v1_plugin_proto_depIdxs = nil
}
